services:
  onos:
    image: onosproject/onos:2.7-latest
    container_name: onos
    hostname: onos
    privileged: true
    networks:
      default:
        ipv4_address: 192.168.100.1
    environment:
      - ONOS_APPS=drivers,fpm,org.onosproject.openflow,org.onosproject.gui2 
    ports:
      - "2620:2620"
      - "6653:6653"
      - "8101:8101"
      - "8181:8181"
    tty: true
    stdin_open: true
    command: >
      /bin/bash -c "onos-service start && onos localhost cfg set org.onosproject.provider.nil.NullProvidersProvider openflow.ofp-version 1.4"
  h2:
    image: host
    container_name: h2
    privileged: true
    build:
      context: .
      dockerfile: host.Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      br0:
        ipv4_address: 172.17.40.2
        ipv6_address: 2a0b:4e07:c4:140::2
    # entrypoint: ["/bin/sh","-c"]
  
  h1:
    image: host
    container_name: h1
    privileged: true
    build:
      context: .
      dockerfile: host.Dockerfile
    network_mode: none
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    # entrypoint: ["/bin/sh","-c"]

  RClient:
    image: router
    container_name: RClient
    hostname: RClient
    privileged: true
    build:
      context: .
      dockerfile: router.Dockerfile
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      br0:
        ipv4_address: 172.17.40.1
        ipv6_address: 2a0b:4e07:c4:140::1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/RClient/frr.conf:/etc/frr/frr.conf

  RMain:
    image: router
    container_name: RMain
    hostname: RMain
    privileged: true
    build:
      context: .
      dockerfile: router.Dockerfile
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      default:
        ipv4_address: 192.168.100.3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config/daemons:/etc/frr/daemons
      - ./config/RMain/frr.conf:/etc/frr/frr.conf

networks:
  default:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.254
  br0:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.17.40.0/24
          gateway: 172.17.40.254
        - subnet: 2a0b:4e07:c4:140::/64
          gateway: 2a0b:4e07:c4:140::254